language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "4.0"
# command to run tests
install: pip install --upgrade pip
env:
  - TEST_PY=1
script:
  - python main.py
