# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, feature/github_workflow]
  pull_request:
    branches: [ master, feature/github_workflow ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Update sources 
      uses: actions/checkout@v2   
    - name: Build docker with debug version for smoke test
      run: docker build -t smoke_test_app --file Dockerfile.smoke .
    - name: Build tests docker image
      run: docker build -t test_app --file Dockerfile.tests .
    - name: Start docker with smoke test
      run: docker run -t smoke_test_app 
    - name: Start testz 
      run: docker run -t test_app
    - name: Build package for deploying
      run: docker build . --file Dockerfile.app -t serfdanilov/phonebook:2020.beta01-$GITHUB_RUN_NUMBER
    - name: Deploy ready package
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push ${{ secrets.DOCKER_USERNAME }}/phonebook:2020.beta01-$GITHUB_RUN_NUMBER
  
  
  codeStyleCheck:
    runs-on: [ubuntu-latest]
    steps:
    - name: Check code style
      
      run: pip install pep8; python -m pep8 ./main.py ./database.py ./core.py
